### ISSUE TITLE
Link unfurling

### ISSUE THREAD

**Issue by renatolond** [kudos/match.audio#14]
When posting an Match.audio link in Telegram or Slack, the link is unfurling to the default description/title. Instead, it would be better try to unfurl to the media you're linking to.

https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254#.7fm7rnuw4

**Comment by renatolond** [comment]
I'm thinking on starting a PR on this, what do you think?

**Comment by kudos** [comment]
Looks like I broke this in a refactor (probably when upgrading React et al), you can see [here](https://github.com/kudos/match.audio/blob/master/views/head.js#L8-L10) how it used to work. I'd like to fix it, but if you think you can get to it sooner that would be awesome.

**Comment by renatolond** [comment]
Hey!
I stopped to take a look at this today.
The problem seems to be that on `react_handler.js`, when calling `RoutingContext`, it doesn't pass state ahead (which contains the `shares` which are used on `head.js`).
I couldn't find a way to pass shares ahead, except by changing renderProps to have shares in its params. I don't know if this is the better way, I'm not really a react guy.
Anyway, I'm opening a PR and you can tell there if you think there's a better way to do it.

**Comment by kudos** [comment]
This is fixed!
