### ISSUE TITLE
Ability to select a default service

### ISSUE THREAD

**Issue by JohnMaguire** [kudos/match.audio#15]
I think it'd be neat to be able to choose a music provider as a "default" when hitting the results page without having just submitted the form. On the next match.audio link you clicked, you'd be sent directly to that music provider if it was available, or told to select a different source. Probably there'd be a 3 second wait before redirection or something so you could change your preferred music provider. I think you could just set a cookie with the provider they selected.

This way if people were sending match.audio links frequently, you wouldn't have to "click through" each time. I'd like to use match.audio in my IRC bot (for example, during the Last.fm-backed "now playing" command to link the song they are listening to), so if people were frequently clicking links in the channel, they wouldn't have to click Spotify or YouTube every time, for example.

**Comment by matthewdias** [comment]
dupe of #1?

**Comment by JohnMaguire** [comment]
Hahaha, totes forgot.
