### ISSUE TITLE
Link wrong when sharing track from Google Play

### ISSUE THREAD

**Issue by renatolond** [kudos/match.audio#19]
Hello!

I've tried to share a track from google play today: https://play.google.com/music/m/Tfdfxstnbkqwnzeg5xtkg64sjgy?signup_if_needed=1
Which goes to this link: https://match.audio/google/track/Tfdfxstnbkqwnzeg5xtkg64sjgy

But looking at the json returned: https://match.audio/google/track/Tfdfxstnbkqwnzeg5xtkg64sjgy.json

You can see that the track is giving out the wrong type `album`. I've started match.audio locally and did some debugging, and it seems that `this.getDataValue('trackId')` which is used in the comparison at `models/track.js:32` is never there. Given that this is inside the `Track` model, can it be an album at some point? I've tried changing this to getter to something like this instead:
```
      type() {
        return 'track';
      },  
```
And did a similar thing in the album getter, and it seems the answers become right. There's a similar issue in `lib/share.js:77`. In there I changed to:
```
          models.match.create({
            trackId: share.$modelOptions.name.singular == 'track' ? share.id : null,
            albumId: share.$modelOptions.name.singular == 'album' ? share.id : null,
            externalId: null,
            service: match.service,
            name: null,
            streamUrl: null,
            purchaseUrl: null,
            artworkSmall: null,
            artworkLarge: null,
          });
```

Does this makes sense to you?
You can see the diff in here:
https://github.com/kudos/match.audio/compare/master...renatolond:music_type_fix

**Comment by kudos** [comment]
I've applied the patch, thanks for looking into it :)
