### ISSUE TITLE
Search box only appears from internal links

### ISSUE THREAD

**Issue by renatolond** [kudos/match.audio#21]
If I open match.audio straight from the link bar, I don't have the search box, see attached screenshot:
![image](https://cloud.githubusercontent.com/assets/173791/26025544/8558de9c-37ea-11e7-89e5-52a8b9f142d1.png)

But if I visit a recently searched album and then come back to the main page using the match.audio link at the top, the search bar is back:
![image](https://cloud.githubusercontent.com/assets/173791/26025548/9af284f6-37ea-11e7-82a0-61af17ab2869.png)

This was not the case a few days ago, when I could just hit up match.audio and search directly. It seems that the search is being removed in the entry-client.js, when it does replaceState. Which seems it's not called when navigating from an existing page.

**Comment by kudos** [comment]
I disabled Cloudflare's HTML which was breaking VueJS's pre-rendered HTML getting rehydrated correctly on the client. It's looking good to me now, thanks for the report!
